feat: create request test by category page (dbio-308)
debionetwork/debio-frontend pull request #125
Opened 2021-08-10 06:17 UTC by ciniiia

### JIRA Link
https://blocksphere2020.atlassian.net/browse/DBIO-308?atlOrigin=eyJpIjoiNjNkNzRlN2I1ODI3NGFmMTliZDIxMGQ2ZGQ3NTVhM2QiLCJwIjoiaiJ9

### Changelog / Description
- create page request test by category

2021-08-10 08:48 UTC, bukandicki commented
LGTM 👍🏻
ada beberapa hal kecil aja soal konsistensi penggunaan tanda petik

2021-08-10 09:00 UTC, bukandicki requested changes

2021-08-13 13:07 UTC, ciniiia commented on src/views/Dashboard/Customer/RequestTest/FindTest.vue
> +      return this.cities
mas @bukandicki, minta tolong di reviewin lagi yaa. thank you

2021-08-14 06:47 UTC, bukandicki approved these changes

2021-08-14 06:47 UTC, bukandicki commented on src/views/Dashboard/Customer/RequestTest/FindTest.vue
> +      return this.cities
done mbak @ciniiia

2021-08-14 23:24 UTC, kevinjanada approved these changes

2021-08-25 05:02 UTC, kevinjanada commented
Akan dibuat PR baru karena ada perubahan requirements

2021-08-25 05:02 UTC, closed without merging