feat: add link to binding wallet when checkout (DBIO-404)
debionetwork/debio-frontend pull request #128
Opened 2021-08-12 04:07 UTC by ciniiia

### JIRA Link
https://blocksphere2020.atlassian.net/browse/DBIO-404?atlOrigin=eyJpIjoiNzk0NWE3Y2I2NjZkNDMyY2JmYzQ5NDI5NWQwODA2MzAiLCJwIjoiaiJ9

### Changelog / Description
- add button that will directing user to binding wallet when checkout, if wallet has not been connected yet

2021-08-12 06:33 UTC, bukandicki commented on src/views/Dashboard/Customer/RequestTestCheckout/index.vue
> +      @status-wallet="({ status, img }) => connectWalletResult(status, img)"
LGTM mbak @ciniiia 👍🏻 
Cuman bagusnya ini di buat method khususnya aja , hindarin inline method kaya gini mbak @ciniiia biasanya sering ada unexpected error

2021-08-12 06:34 UTC, bukandicki approved these changes

2021-08-13 07:49 UTC, kevinjanada commented on .gitignore
> +package-lock-json
package-lock-json ini setauku sebaiknya jgn di gitignore ya. mnurut kalian gmn?
@ciniiia @bukandicki @luthfiazhari

2021-08-13 10:25 UTC, bukandicki commented on .gitignore
> +package-lock-json
yep setuju mas, supaya kepantau terus mas 👍🏻

2021-08-13 11:42 UTC, kevinjanada commented on .gitignore
> +package-lock-json
aku request change ya mba @ciniiia

2021-08-13 11:43 UTC, kevinjanada requested changes
minta tolong package-lock-json nya tidak usah di ignore ya mba

2021-08-13 12:33 UTC, ciniiia commented on .gitignore
> +package-lock-json
okayy siap mas mas 👍🏻

2021-08-14 22:50 UTC, kevinjanada approved these changes

2021-08-14 22:51 UTC, merged