feat: customer request service and staking coin (dbio-474)
debionetwork/debio-frontend pull request #144
Opened 2021-08-18 02:48 UTC by ciniiia

### JIRA Link
https://blocksphere2020.atlassian.net/browse/DBIO-474?atlOrigin=eyJpIjoiNTExNDM1NDU3NDM3NGQ5YWJhZjEyNzQyM2RmZWYyZjQiLCJwIjoiaiJ9

### Changelog / Description

- create page for request service
- create staking coin agreement dialog

2021-08-19 11:05 UTC, bukandicki commented on src/views/Dashboard/Customer/RequestTest/FindLab.vue
> +              :disabled="isLoadingRequestNoLab || category.length == 0"
Mbak @ciniiia ini gapapa masukin aja ke `computed`

2021-08-19 11:05 UTC, bukandicki commented on src/views/Dashboard/Customer/RequestTest/FindLab.vue
> +      if (this.showNoLab) {
Karna ini singkat/pendek statementnya baiknya di giniin aja mbak @ciniiia 

```js
if (this.showNoLab) return 'There are no available lab'
else return 'Select Test Lab'
```
atau
```js
if (this.showNoLab) return 'There are no available lab'

return 'Select Test Lab'
```

2021-08-19 11:08 UTC, bukandicki requested changes
LGTM 👍🏻 cuman ada beberapa hal contohnya dibawah sini 👇🏻

2021-08-19 11:08 UTC, bukandicki commented on src/views/Dashboard/Customer/RequestTest/FindLab.vue
> +      if (category == "Other") {
ini juga sama mbak @ciniiia ikutin aja cara yang penerapan `if` di comment sebelumnya

2021-08-19 11:08 UTC, bukandicki commented on src/views/Dashboard/Customer/RequestTest/StakingDialog.vue
> +          :disabled="!agree || isLoading || !amount"
ini gapapa mbak di pindahin ke `computed` aja

2021-08-25 05:00 UTC, kevinjanada commented
Akan dibikin PR baru karena ada perubahan requirements

2021-08-25 05:00 UTC, closed without merging