fix: fix validation on lab
debionetwork/debio-frontend pull request #312
Opened 2021-12-21 17:35 UTC by luthfiazhari

### JIRA Link
URL to your task/ticket number in JIRA (if applicable)
If there's no JIRA ticket number, describe why in description below.

### Changelog / Description
The description of your task or what is changed.
e.g: Update substrate config, new feature / bugfix, etc.

2021-12-22 07:23 UTC, hilyds reviewed
this doesn't resolve the DBIO-1361, but only field validation. please check some comment above

2021-12-22 07:23 UTC, hilyds commented on src/views/Dashboard/Lab/Account/Certification.vue
> +                    label="Supporting Documentsss"
do you forgot to change this?

2021-12-22 07:23 UTC, hilyds commented on src/views/Dashboard/Lab/Account/Certification.vue
> -                    accept="application/pdf, image/png, image/jpeg,"
it doesn't support png/jpeg?

2021-12-22 12:47 UTC, luthfiazhari commented on src/views/Dashboard/Lab/Account/Certification.vue
> +                    label="Supporting Documentsss"
yes my bad, i already fix this

2021-12-23 01:29 UTC, hilyds requested changes
please do checkout some of my comments

2021-12-23 01:29 UTC, hilyds commented on src/views/Dashboard/Customer/EMR/UploadEMR.vue
> +        val => (val && val.length <= 50) || 'This field only allows 255 characters'
The validation is <=50, but the text ist 255 characters. Please fix which one is true

2021-12-23 01:29 UTC, hilyds commented on src/views/Dashboard/Doctor/Account/Certification.vue
>          val => (val && val.length <= 50) || 'Max 50 Character'
should the message validation be the same : 'This field only allows 50 characters' ?

2021-12-23 01:29 UTC, hilyds commented on src/views/Dashboard/Doctor/Account/Certification.vue
>          val => (val && val.length <= 100) || 'Max 100 Character']
should the message validation be the same : 'This field only allows 100 characters' ?

2021-12-23 01:29 UTC, hilyds commented on src/views/Dashboard/Doctor/Account/Verification.vue
> +        value => !value || value.size < 2000000 || 'The total file size uploaded exceeds the maximum file size allowed (2MB',
miss the ')' at the end of the sentence

2021-12-23 01:29 UTC, hilyds commented on src/views/Dashboard/Doctor/Registration/index.vue
>          val => /.+@.+\..+/.test(val) || 'E-mail must be valid',
Make the error message consistent with other email field validation :
Email is invalid. It should contain @ followed by a domain

2021-12-23 01:29 UTC, hilyds commented on src/views/Dashboard/Hospital/Account/Certification.vue
>          val => (val && val.length <= 50) || 'Max 50 Character'
Make the error message consistent with other field validation :
This field only allows 50 characters'

2021-12-23 01:29 UTC, hilyds commented on src/views/Dashboard/Hospital/Account/Certification.vue
>          val => (val && val.length <= 100) || 'Max 100 Character']
Make the error message consistent with other field validation :
This field only allows 100 characters'

2021-12-23 01:29 UTC, hilyds commented on src/views/Dashboard/Hospital/Registration/index.vue
>          val => /.+@.+\..+/.test(val) || 'E-mail must be valid',
Make the error message consistent with other email field validation :
Email is invalid. It should contain @ followed by a domain

2021-12-23 01:29 UTC, hilyds commented on src/views/Dashboard/Lab/Account/index.vue
>          file => !file || file.type == 'image/jpg' || file.type == 'image/jpeg' || 'Document type should be image/jpg',
should also mention 'jpeg' in the error message. also, png format should also supported

2021-12-23 01:29 UTC, hilyds commented on src/views/Dashboard/Lab/Registration/Services/index.vue
> +    selectExpectedDuration: 'Working Day',
why change this line?

2021-12-23 01:29 UTC, hilyds commented on src/views/Dashboard/Lab/Registration/Services/index.vue
> +      console.log(this.expectedDuration, "expected duration")
need to remove this line and the line below

2021-12-23 01:29 UTC, hilyds commented on src/views/Dashboard/Lab/Registration/index.vue
> +    phoneNumberRules() {// validasi di exel belom ada
the comment in here, use english next time. so it's still need to fix?

2021-12-23 11:26 UTC, merged