[DBIO-1768] Few issues on step 1 registration
debionetwork/debio-frontend pull request #360
Opened 2022-02-04 01:50 UTC by luthfiazhari

### JIRA LINK 🟦
- https://blocksphere2020.atlassian.net/browse/DBIO-1768

### Changelog/Description 🗒️
- Refactor code for get publicKey on lab registration

### WARNING ⚠️
- 

### Screenshoot/Video (Optional) 🖼️

2022-02-08 08:19 UTC, agustinustheo requested changes
What is this PR trying to fix?

2022-02-08 08:19 UTC, agustinustheo commented on src/views/Dashboard/Lab/Registration/index.vue
> +    console.log(cred, "creeeeeed")
Remove console logs please.

2022-02-08 10:14 UTC, luthfiazhari commented
> What is this PR trying to fix?

This PR is fix code how to get publicKey from mnemonic data. earlier in this code, do not decrypt mnemonic data. so the public key is not found.

2022-02-08 10:16 UTC, luthfiazhari commented
i think i push my code to wrong branch, please refer to this PR https://github.com/debionetwork/debio-frontend/pull/362 @agustinustheo. this PR can be closed

2022-02-11 03:48 UTC, bukandicki requested changes

2022-02-11 03:48 UTC, bukandicki commented on src/components/Button/index.vue
> +    v-bind="bind"
why are you using these props? vue already provides $listeners and $attrs please update it instead of you using props for this one

2022-02-11 03:48 UTC, bukandicki commented on src/components/Button/index.vue
> +    bind: [Boolean, String, Function, Object]
please remove these props after you using listeners and attrs

2022-02-11 03:48 UTC, bukandicki commented on src/views/Dashboard/Lab/Registration/index.vue
> +    console.log(secretKey, "secret")
this too, please remove these consoles

2022-02-11 19:48 UTC, closed without merging

2022-02-11 19:49 UTC, agustinustheo commented
> i think i push my code to wrong branch, please refer to this PR #362 @agustinustheo. this PR can be closed thankyou

Closed, requested by @luthfiazhari