[DBIO-1401] Fix: service image mismatch lab
debionetwork/debio-frontend pull request #368
Opened 2022-02-20 20:17 UTC by luthfiazhari

### JIRA LINK 🟦
- https://blocksphere2020.atlassian.net/browse/DBIO-1401

### Changelog/Description 🗒️
- fix service image mismatch on lab

### WARNING ⚠️
- 

### Screenshoot/Video (Optional) 🖼️

2022-02-20 21:30 UTC, agustinustheo requested changes

2022-02-20 21:30 UTC, agustinustheo commented on src/views/Dashboard/Lab/Services/index.vue
> +      return "https://ipfs.io/ipfs/QmZveuvcQAbkcbcop28iqWrnCMoxN2n5SGzA3Hwr1cJ61i/debio-logo.png"
The DeBio logo shouldn't be hardcoded like this. Wouldn't it be better to turn it into an Icon? @luthfiazhari.

Please ask @bukandicki for help. @bukandicki, please help @luthfiazhari with this.

2022-02-21 03:55 UTC, agustinustheo commented on src/views/Dashboard/Lab/Services/index.vue
> +      return "https://ipfs.io/ipfs/QmZveuvcQAbkcbcop28iqWrnCMoxN2n5SGzA3Hwr1cJ61i/debio-logo.png"
Example: https://github.com/debionetwork/debio-customer-ui/pull/309/commits/1c248c86dc174be12e1d4b3a1e4a55791a4ca96a

2022-03-13 21:42 UTC, agustinustheo commented
Closing because of inaction @luthfiazhari

2022-03-13 21:42 UTC, closed without merging

2022-03-29 02:56 UTC, luthfiazhari commented
this PR is not relevan again with current task.