[DBIO-2078] refactor: take out get-dbio-pre-register
debionetwork/debio-frontend pull request #375
Opened 2022-03-22 09:56 UTC by azmimuhammad

### JIRA LINK 🟦
- https://blocksphere2020.atlassian.net/browse/DBIO-2078

### Changelog/Description 🗒️
- take out get-dbio-pre-register

### WARNING ⚠️
- 

### Screenshoot/Video (Optional) 🖼️

2022-03-22 17:16 UTC, agustinustheo requested changes

2022-03-22 17:16 UTC, agustinustheo commented on src/store/index.js
> +// import registration from './registration'
Why is this commented, not deleted?

2022-03-22 17:16 UTC, agustinustheo commented on src/views/Dashboard/Lab/NavigationLayout.vue
> +// import localStorage from "@/lib/local-storage";
Why is this commented, not deleted?

2022-03-23 02:02 UTC, azmimuhammad commented on src/views/Dashboard/Lab/NavigationLayout.vue
> +// import localStorage from "@/lib/local-storage";
sorry, i forgot when i testing it

2022-03-23 02:02 UTC, azmimuhammad commented on src/views/Dashboard/Lab/NavigationLayout.vue
> +// import localStorage from "@/lib/local-storage";
updated, thanks a lot @agustinustheo

2022-03-23 03:47 UTC, agustinustheo approved these changes

2022-03-23 03:47 UTC, merged