fix: Lab several issues
debionetwork/debio-frontend pull request #496
Opened 2022-08-12 09:36 UTC by bukandicki

### JIRA LINK 🟦
- https://blocksphere2020.atlassian.net/browse/DBIO-2928
- https://blocksphere2020.atlassian.net/browse/DBIO-2870

### Changelog/Description 🗒️
- add dynamic watch URL params
- fix Lab notification
- fix refill number

### WARNING ⚠️
- 

### Screenshoot/Video (Optional) 🖼️

2022-08-15 06:38 UTC, agustinustheo approved these changes

2022-08-16 05:31 UTC, agustinustheo requested changes
Why wrap it in a try catch?

2022-08-16 07:27 UTC, bukandicki commented
> Why wrap it in a try catch?

`UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "TypeError: Cannot read properties of undefined (reading 'params')"`

I think the error is saying that this is not working properly because it is not handled using `try catch`, so I added that. And now it's going well

2022-08-19 04:07 UTC, agustinustheo commented
I'm merging anyway by request from QA team.

2022-08-19 04:07 UTC, merged